<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>Kobayashi Ryu</Authors>
    <PackageTags>LoL, Riot, LeagueOfLegends</PackageTags>
    <Description>Easily get CDragon's data.</Description>
    <AssemblyVersion>2.1.0</AssemblyVersion>
    <Version>$(VersionPrefix)2.1.0</Version>
  </PropertyGroup>

</Project>
